server:
  port: 31415
spring:
  data:
    mongodb:
      # uri方式连接池参数过多不好看
#      uri: mongodb://yuyunhu:123456@192.168.83.141:27017/yyh-cmdb?authSource=admin&minPoolSize=10&maxPoolSize=50
      host: 192.168.83.141
      port: 27017
      database: yyh-cmdb
      username: yuyunhu
      password: "123456"   # 不加引号会报错：java.lang.IllegalArgumentException: Prohibited character at position 0
      authentication-database: admin  # 这个认证在使用uri方式的时候需要以参数的形式写在uri后面
      # 连接池配置
      connection:
        socket-timeout: 2000  # 连接超时时间，单位是毫秒，默认是0（无限制）
        min-connections: 10  # 连接池中保持的最小连接数
        max-connections: 50  # 连接池中允许的最大连接数
        max-wait-queue-size: 100  # 等待队列的最大大小
        max-connection-idle-time: 60000  # 连接在空闲状态下保持打开的最大时间（毫秒）
        max-connection-life-time: 1800000  # 连接在池中可以存在的最长时间（毫秒）
        maintenance:
          initial-delay: 30000  # 连接池维护任务的初始延迟时间（毫秒）
          frequency: 60000  # 连接池维护任务执行的频率（毫秒）
          task-time: 0  # 连接池维护任务执行的时间长度（毫秒）
